import { useMemo, useState } from "react";
import type { Child } from "@bala/shared";
import { ArrowRight, Baby, CalendarDays, Info, Loader2, LockKeyhole, MousePointer2, Save, X } from "lucide-react";
import { cdcBoys2to20, cdcGirls2to20 } from "../who/cdc-2-20";
import type { LmsReferencePoint } from "../who/cdc-2-20";
import InteractiveGrowthChart, { type GrowthMetric } from "./InteractiveGrowthChart";

type Props={child:Child;date:string;maxDate:string;saving:boolean;onDateChange:(v:string)=>void;onCancel:()=>void;onSave:(v:{date:string;height:number;weight:number})=>Promise<void>};
const parseUtc=(v:string)=>new Date(`${v}T00:00:00.000Z`);
const zCuts=[[-1.644854,"P5"],[-1.281552,"P10"],[-.67449,"P25"],[0,"P50"],[.67449,"P75"],[1.281552,"P90"],[1.644854,"P95"]] as const;
const decimalAge=(birth:Date,date:Date)=>Math.max(0,(date.getTime()-birth.getTime())/(365.2425*86400000));
const getReference=(gender:Child["gender"])=>gender==="male"?cdcBoys2to20:cdcGirls2to20;
function interpolate(reference:LmsReferencePoint[],ageMonths:number,metric:GrowthMetric){let upper=reference.findIndex(r=>r.ageMonths>=ageMonths);if(upper<=0)return reference[Math.max(0,upper)][metric];if(upper<0)return reference.at(-1)![metric];const a=reference[upper-1],b=reference[upper],t=(ageMonths-a.ageMonths)/(b.ageMonths-a.ageMonths);return a[metric].map((v,i)=>v+(b[metric][i]-v)*t) as [number,number,number];}
function assessment(value:number|null,lms:readonly[number,number,number]){if(value===null)return null;const[l,m,s]=lms,z=l===0?Math.log(value/m)/s:(Math.pow(value/m,l)-1)/(l*s);let label="P50",distance=Infinity;for(const[cut,name]of zCuts){if(Math.abs(z-cut)<distance){distance=Math.abs(z-cut);label=name;}}return{z:Number(z.toFixed(2)),label};}
const displayDate=(v:string)=>v.split("-").reverse().join(".");

export default function PlotMeasurement({child,date,maxDate,saving,onDateChange,onCancel,onSave}:Props){
 const[step,setStep]=useState<GrowthMetric>("height"),[height,setHeight]=useState<number|null>(null),[weight,setWeight]=useState<number|null>(null);
 const measureDate=parseUtc(date),exactYears=decimalAge(child.birthDate,measureDate),ageMonths=exactYears*12,completedMonths=Math.max(0,Math.floor(ageMonths));
 const years=Math.floor(completedMonths/12),months=completedMonths%12,reference=getReference(child.gender),inRange=exactYears>=2&&exactYears<20&&measureDate>=child.birthDate&&measureDate<=parseUtc(maxDate),selected=step==="height"?height:weight;
 const result=useMemo(()=>assessment(selected,interpolate(reference,ageMonths,step)),[selected,reference,ageMonths,step]);
 const heightResult=height===null?null:assessment(height,interpolate(reference,ageMonths,"height"));
 function changeDate(v:string){onDateChange(v);setHeight(null);setWeight(null);setStep("height");}
 async function save(){if(height===null||weight===null||!inRange)return;await onSave({date,height,weight});setHeight(null);setWeight(null);onCancel();}
 return <div className="fixed inset-0 z-50 flex bg-slate-950/35 p-2 backdrop-blur-[2px] sm:p-5" role="dialog" aria-modal="true" aria-label="Plot measurement on growth chart"><div className="m-auto flex max-h-[96vh] w-full max-w-[1500px] flex-col overflow-hidden rounded-2xl border border-slate-300 bg-white shadow-2xl">
  <header className="flex items-center justify-between border-b border-slate-200 px-6 py-5"><h2 className="text-xl font-bold text-slate-900">Plot measurement on growth chart</h2><button type="button" onClick={onCancel} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Close"><X size={22}/></button></header>
  <div className="min-h-0 flex-1 overflow-auto lg:grid lg:grid-cols-[390px_minmax(0,1fr)]"><aside className="flex flex-col border-r border-slate-200 p-6">
   <div className="grid grid-cols-2 gap-3"><StepButton active={step==="height"} number="1" label="Height (stature)" onClick={()=>setStep("height")}/><StepButton active={step==="weight"} number="2" label="Weight" disabled={height===null} onClick={()=>setStep("weight")}/></div>
   <label className="mt-7 text-sm font-bold text-slate-900">Measurement date<div className="relative mt-3"><CalendarDays className="absolute left-4 top-3 text-slate-400" size={18}/><input type="date" value={date} min={child.birthDate.toISOString().slice(0,10)} max={maxDate} onChange={e=>changeDate(e.target.value)} className="w-full rounded-lg border border-slate-300 py-2.5 pl-11 pr-3 outline-none focus:border-blue-500"/></div></label>
   <div className="mt-6 text-sm font-bold">Child age on this date</div><div className="mt-3 flex items-center gap-4 rounded-xl border border-teal-100 bg-teal-50/70 p-4"><Baby className="text-teal-500"/><div><div className="text-lg font-bold">{years} years {months} months</div><div className="text-sm text-slate-500">({exactYears.toFixed(2)} years)</div></div></div>
   {!inRange?<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Select a date when the child is between 2 and 20 years old.</div>:<><div className="mt-5 flex gap-3 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-700"><Info className="mt-0.5 shrink-0" size={20}/>Click on the chart at the vertical age line to select {step}.</div><div className="mt-5 rounded-xl border border-slate-200 p-5"><div className="text-sm font-bold">Selected {step}</div><div className="mt-4 flex items-center justify-between"><div className="text-3xl font-bold text-blue-600">{selected?.toFixed(1)??"—"} {step==="height"?"cm":"kg"}</div>{result&&<span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-700">{result.label}</span>}</div><div className="mt-3 text-slate-500">Z-score: {result?.z.toFixed(2)??"—"}</div></div><div className="mt-5 flex gap-3 rounded-xl border border-blue-100 bg-blue-50/60 p-4"><MousePointer2 className="shrink-0 text-blue-600"/><div><div className="font-bold text-blue-700">How to use</div><p className="mt-1 text-sm leading-6 text-slate-600">Click anywhere along the vertical dotted line to select the child's {step} for the selected age.</p></div></div></>}
   <div className="mt-auto grid grid-cols-2 gap-3 pt-8"><button type="button" onClick={onCancel} className="rounded-lg border border-slate-300 px-4 py-3 font-semibold">Cancel</button>{step==="height"?<button type="button" disabled={height===null} onClick={()=>setStep("weight")} className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-40">Next: Weight <ArrowRight size={18}/></button>:<button type="button" disabled={weight===null||saving} onClick={()=>void save()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-40">{saving?<Loader2 className="animate-spin" size={18}/>:<Save size={18}/>}Save</button>}</div>
  </aside><main className="min-w-0 p-6"><div className="mb-4 flex items-start justify-between"><div><h3 className="font-bold text-slate-900">Stature-for-age and Weight-for-age percentiles</h3><p className="mt-1 text-sm">{child.gender==="male"?"Boys":"Girls"}, 2 to 20 years</p></div><div className="rounded-lg border border-slate-200 p-1"><span className="inline-block rounded-md bg-blue-600 px-3 py-1.5 text-sm font-bold text-white">cm</span><span className="inline-block px-3 py-1.5 text-sm text-slate-500">in</span></div></div>{inRange?<InteractiveGrowthChart activeMetric={step} ageMonths={ageMonths} reference={reference} height={height} weight={weight} onSelect={(metric,v)=>metric==="height"?setHeight(v):setWeight(v)}/>:<div className="flex h-[600px] items-center justify-center rounded-xl border border-dashed border-slate-300 bg-slate-50 text-slate-500">Choose a supported measurement date to display the chart.</div>}<div className="mt-3 text-right text-xs font-medium text-blue-600">SOURCE: CDC Growth Charts (2000)</div></main></div>
  <footer className="grid items-center gap-4 border-t border-blue-100 bg-blue-50/50 px-6 py-4 text-center text-sm sm:grid-cols-[repeat(4,1fr)_230px]"><Summary label="Date" value={displayDate(date)}/><Summary label="Age" value={`${years} years ${months} months`}/><Summary label="Height" value={`${height?.toFixed(1)??"—"} cm${heightResult?` (${heightResult.label})`:""}`} blue/><Summary label="Weight" value={`${weight?.toFixed(1)??"—"} kg`}/><button type="button" disabled={height===null||weight===null||saving} onClick={()=>void save()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-5 py-3 font-bold text-white disabled:bg-slate-200 disabled:text-slate-400">{height===null||weight===null?<LockKeyhole size={17}/>:<Save size={17}/>}Save measurement</button></footer>
 </div></div>;
}
function StepButton({active,number,label,onClick,disabled=false}:{active:boolean;number:string;label:string;onClick:()=>void;disabled?:boolean}){return <button type="button" disabled={disabled} onClick={onClick} className={`rounded-lg px-4 py-3 text-left text-sm font-semibold disabled:opacity-45 ${active?"bg-blue-600 text-white":"border border-slate-200 bg-slate-50 text-slate-600"}`}><span className="mr-2 rounded-full border px-1.5 py-0.5">{number}</span>{label}</button>}
function Summary({label,value,blue=false}:{label:string;value:string;blue?:boolean}){return <div className="sm:border-l sm:border-slate-300"><div className="text-slate-500">{label}</div><b className={blue?"text-blue-600":""}>{value}</b></div>}
